/* programmes.js
 *
 * All 25 preset walking/running programmes, transcribed from the
 * programmes array Nigel already had built into his updated
 * index.html (desktop app), converted into the {name, desc,
 * segments:[{label, duration_s, speed_kmh}]} shape the programme
 * player in app.js expects.
 */

window.WalkPadProgrammes = [
  { id: 1, name: "10 Min Gentle Starter", desc: "10 min \u2022 Warm stroll from 1.5 to 2.5 km/h", segments: [{ label: "Warm Up", duration_s: 180, speed_kmh: 1.5 }, { label: "Brisk Stroll", duration_s: 300, speed_kmh: 2.5 }, { label: "Cool Down", duration_s: 120, speed_kmh: 1.5 }] },
  { id: 2, name: "15 Min Beginner Stroll", desc: "15 min \u2022 Easy pace 2.0 to 3.5 km/h", segments: [{ label: "Warm Up", duration_s: 180, speed_kmh: 2 }, { label: "Brisk Walk", duration_s: 540, speed_kmh: 3.5 }, { label: "Cool Down", duration_s: 180, speed_kmh: 1.8 }] },
  { id: 3, name: "20 Min Daily Vitality", desc: "20 min \u2022 Steady 3.0 to 4.0 km/h walk", segments: [{ label: "Warm Up", duration_s: 240, speed_kmh: 2.5 }, { label: "Active Walk", duration_s: 720, speed_kmh: 4 }, { label: "Cool Down", duration_s: 240, speed_kmh: 2 }] },
  { id: 4, name: "20 Min Post-Meal Digest", desc: "20 min \u2022 Light 2.5 km/h continuous pace", segments: [{ label: "Gentle Walk", duration_s: 1080, speed_kmh: 2.5 }, { label: "Cool Down", duration_s: 120, speed_kmh: 1.8 }] },
  { id: 5, name: "25 Min Step Booster", desc: "25 min \u2022 Step up from 2.0 to 4.5 km/h", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 2 }, { label: "Phase 1", duration_s: 600, speed_kmh: 3.5 }, { label: "Phase 2", duration_s: 300, speed_kmh: 4.5 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2 }] },
  { id: 6, name: "30 Min Intermediate Workout", desc: "30 min \u2022 Progressive speeds up to 6.4 km/h", segments: [{ label: "Warm Up", duration_s: 180, speed_kmh: 1.5 }, { label: "Stage 1", duration_s: 300, speed_kmh: 6 }, { label: "Stage 2", duration_s: 300, speed_kmh: 6.3 }, { label: "Peak Training", duration_s: 240, speed_kmh: 6.4 }, { label: "Stage 4", duration_s: 240, speed_kmh: 6.3 }, { label: "Stage 5", duration_s: 240, speed_kmh: 6 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.6 }] },
  { id: 7, name: "30 Min Speed Builder", desc: "30 min \u2022 Incremental speed boosts", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Tempo 1", duration_s: 480, speed_kmh: 4.5 }, { label: "Tempo 2", duration_s: 480, speed_kmh: 5.5 }, { label: "Peak Tempo", duration_s: 240, speed_kmh: 6 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 8, name: "35 Min Aerobic Burn", desc: "35 min \u2022 Sustained moderate pace", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Steady Cardio", duration_s: 1500, speed_kmh: 5 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 9, name: "40 Min Advanced Endurance", desc: "40 min \u2022 High intensity walking & jogging", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Tempo Pace", duration_s: 600, speed_kmh: 5 }, { label: "Sprint Interval", duration_s: 300, speed_kmh: 7 }, { label: "Active Recovery", duration_s: 300, speed_kmh: 4 }, { label: "Sprint Interval", duration_s: 300, speed_kmh: 7 }, { label: "Cool Down", duration_s: 600, speed_kmh: 2.5 }] },
  { id: 10, name: "45 Min Distance Stride", desc: "45 min \u2022 Long distance steady exercise", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3.5 }, { label: "Cruising Speed", duration_s: 2100, speed_kmh: 5.2 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 11, name: "15 Min Fast Express Intervals", desc: "15 min \u2022 Short high-intensity bursts", segments: [{ label: "Warm Up", duration_s: 180, speed_kmh: 3 }, { label: "Fast Pace", duration_s: 120, speed_kmh: 6 }, { label: "Recovery", duration_s: 120, speed_kmh: 3.5 }, { label: "Fast Pace", duration_s: 120, speed_kmh: 6 }, { label: "Recovery", duration_s: 120, speed_kmh: 3.5 }, { label: "Cool Down", duration_s: 240, speed_kmh: 2 }] },
  { id: 12, name: "20 Min Fat Burn Intervals", desc: "20 min \u2022 Alternating steady & fast pace", segments: [{ label: "Warm Up", duration_s: 180, speed_kmh: 2.5 }, { label: "High Speed", duration_s: 180, speed_kmh: 5.5 }, { label: "Recovery", duration_s: 120, speed_kmh: 3 }, { label: "High Speed", duration_s: 180, speed_kmh: 5.5 }, { label: "Recovery", duration_s: 120, speed_kmh: 3 }, { label: "High Speed", duration_s: 180, speed_kmh: 5.5 }, { label: "Cool Down", duration_s: 240, speed_kmh: 2 }] },
  { id: 13, name: "25 Min Pyramid Intervals", desc: "25 min \u2022 Step up then step down speed curve", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 2.5 }, { label: "Step 1", duration_s: 240, speed_kmh: 4 }, { label: "Step 2", duration_s: 240, speed_kmh: 5.5 }, { label: "Peak", duration_s: 240, speed_kmh: 6.5 }, { label: "Step 2", duration_s: 240, speed_kmh: 5.5 }, { label: "Step 1", duration_s: 240, speed_kmh: 4 }, { label: "Cool Down", duration_s: 220, speed_kmh: 2 }] },
  { id: 14, name: "30 Min Metabolism Igniter", desc: "30 min \u2022 Calorie burning interval session", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Push 1", duration_s: 300, speed_kmh: 5.8 }, { label: "Rest 1", duration_s: 180, speed_kmh: 3.5 }, { label: "Push 2", duration_s: 300, speed_kmh: 6.2 }, { label: "Rest 2", duration_s: 180, speed_kmh: 3.5 }, { label: "Push 3", duration_s: 300, speed_kmh: 6.5 }, { label: "Cool Down", duration_s: 340, speed_kmh: 2.5 }] },
  { id: 15, name: "30 Min Power Intervals", desc: "30 min \u2022 Power walking & light jogging cycles", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3.2 }, { label: "Jog", duration_s: 240, speed_kmh: 6.8 }, { label: "Walk", duration_s: 180, speed_kmh: 4 }, { label: "Jog", duration_s: 240, speed_kmh: 6.8 }, { label: "Walk", duration_s: 180, speed_kmh: 4 }, { label: "Jog", duration_s: 240, speed_kmh: 6.8 }, { label: "Cool Down", duration_s: 340, speed_kmh: 2.5 }] },
  { id: 16, name: "20 Min Gentle Incline Walk", desc: "20 min \u2022 Simulated hill effort with higher pace", segments: [{ label: "Warm Up", duration_s: 240, speed_kmh: 2.5 }, { label: "Climb", duration_s: 720, speed_kmh: 4.8 }, { label: "Cool Down", duration_s: 240, speed_kmh: 2 }] },
  { id: 17, name: "25 Min Rolling Hills", desc: "25 min \u2022 Oscillating high and moderate speeds", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Hill 1", duration_s: 180, speed_kmh: 5.2 }, { label: "Valley", duration_s: 120, speed_kmh: 3.5 }, { label: "Hill 2", duration_s: 180, speed_kmh: 5.8 }, { label: "Valley", duration_s: 120, speed_kmh: 3.5 }, { label: "Hill 3", duration_s: 180, speed_kmh: 6.2 }, { label: "Cool Down", duration_s: 420, speed_kmh: 2.5 }] },
  { id: 18, name: "30 Min Mountain Climb", desc: "30 min \u2022 Long progressive incline effort", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Base", duration_s: 480, speed_kmh: 4.5 }, { label: "Slope", duration_s: 480, speed_kmh: 5.5 }, { label: "Summit Push", duration_s: 240, speed_kmh: 6.5 }, { label: "Descent Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 19, name: "35 Min Summit Challenge", desc: "35 min \u2022 Extended peak endurance walking", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Ascent", duration_s: 1200, speed_kmh: 5.6 }, { label: "Summit Sprint", duration_s: 300, speed_kmh: 6.8 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 20, name: "40 Min Alpine Trek", desc: "40 min \u2022 High volume stamina workout", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Trek 1", duration_s: 600, speed_kmh: 5 }, { label: "Trek 2", duration_s: 600, speed_kmh: 5.8 }, { label: "Trek 3", duration_s: 600, speed_kmh: 6.2 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 21, name: "15 Min Tabata Sprint", desc: "15 min \u2022 Short max intensity intervals", segments: [{ label: "Warm Up", duration_s: 180, speed_kmh: 3 }, { label: "Sprint", duration_s: 60, speed_kmh: 7.5 }, { label: "Rest", duration_s: 60, speed_kmh: 3 }, { label: "Sprint", duration_s: 60, speed_kmh: 7.5 }, { label: "Rest", duration_s: 60, speed_kmh: 3 }, { label: "Sprint", duration_s: 60, speed_kmh: 7.5 }, { label: "Cool Down", duration_s: 420, speed_kmh: 2 }] },
  { id: 22, name: "20 Min HIIT Cardio Blast", desc: "20 min \u2022 High speed interval challenge", segments: [{ label: "Warm Up", duration_s: 240, speed_kmh: 3 }, { label: "HIIT 1", duration_s: 120, speed_kmh: 7 }, { label: "Recover", duration_s: 120, speed_kmh: 3.5 }, { label: "HIIT 2", duration_s: 120, speed_kmh: 7.2 }, { label: "Recover", duration_s: 120, speed_kmh: 3.5 }, { label: "HIIT 3", duration_s: 120, speed_kmh: 7.5 }, { label: "Cool Down", duration_s: 360, speed_kmh: 2.5 }] },
  { id: 23, name: "30 Min Speed Mastery", desc: "30 min \u2022 High speed agility and stamina", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3.5 }, { label: "Fast Walk", duration_s: 600, speed_kmh: 6 }, { label: "Jogging Peak", duration_s: 600, speed_kmh: 7.2 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 24, name: "45 Min Marathon Builder", desc: "45 min \u2022 High calorie long duration session", segments: [{ label: "Warm Up", duration_s: 300, speed_kmh: 3 }, { label: "Pace 1", duration_s: 1200, speed_kmh: 5.4 }, { label: "Pace 2", duration_s: 900, speed_kmh: 6 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
  { id: 25, name: "60 Min Ultimate Stamina", desc: "60 min \u2022 Full hour ultimate walking challenge", segments: [{ label: "Warm Up", duration_s: 600, speed_kmh: 3 }, { label: "Cruise", duration_s: 2400, speed_kmh: 5.5 }, { label: "Finish Push", duration_s: 300, speed_kmh: 6.5 }, { label: "Cool Down", duration_s: 300, speed_kmh: 2.5 }] },
];
